<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>Azurite-APIs-Secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Messaging.ServiceBus" Version="9.4.1" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" Version="9.4.1" />
    <PackageReference Include="Azure.Data.Tables" Version="12.9.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.22.0" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.20.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.31.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.11.10" />
  </ItemGroup>

</Project>
